---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: webcolor-deployment
  labels:
    app: webcolor-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: webcolor-app
  template:
    metadata:
      labels:
        app: webcolor-app
    spec:
      containers:
      - name: webcolor-app
        image: kodekloud/webapp-color
        ports:
        - containerPort: 8080
#        env:
#        - name: APP_COLOR
#          value: blue
        envFrom:
        - configMapRef:
            name: webcolor-configmap
#        env:
#          # Define the environment variable
#          - name: APP_COLOR
#            valueFrom:
#              configMapKeyRef:
#                # The ConfigMap containing the value you want to assign to SPECIAL_LEVEL_KEY
#                name: webcolor-configmap
#                # Specify the key associated with the value
#                key: APP_COLOR