---
apiVersion: v1
kind: Service
metadata:
  name: http-echo-app-service
spec:
  type: LoadBalancer
  ports:
  - name: http
    protocol: TCP
    targetPort: 5678
    port: 5678
  selector:
    app: http-echo-app
