kind: Cluster
apiVersion: kind.x-k8s.io/v1alpha4
nodes:
- role: control-plane
  extraPortMappings:
  - containerPort: 30950
# pre http-echo app
    hostPort: 5678
  - containerPort: 30953
# pre webcolor app
    hostPort: 8888
